services:
  - type: web
    name: client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run start
    
  - type: web
    name: server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
