export const API_URLS = {
    CARDS: '/api/cards',
    CARD_MEMBER: '/api/cards/member',
    TRANSACTIONS: '/api/transactions',
    CARD_TRANSACTIONS: '/api/transactions/card',
    DEPOSITS: '/api/transactions/deposits',
    MEMBERS: '/api/members',
    FILTERED_MEMBERS: '/api/members/filteredMembers',
    ACCOUNTS: '/api/accounts',
    TEAMS: '/api/teams',
    ACCOUNTS_WITH_CARDS: '/api/accounts/memberAccountsWithCards',
    DEPARTMENTS: '/api/departments',
    STATUSES: '/api/statuses',
    ROLES: '/api/roles',
    AUTHENTICATED: '/api/auth/isAuthenticated',
    AUTH_LOGIN: '/api/auth/login',
    AUTH_LOGOUT: '/api/auth/logout',
    AVATARS: '/api/avatars',
    PHONES: '/api/phones',
    DATES: '/api/dates',
    ADDRESSES: '/api/addresses',
    PROFILES: '/api/profiles',
    SEARCH_KEYWORD: '/api/transactions/search',
    SEARCH_MENU_FOR_MERCHANT: '/api/transactions/search/menu',
    MEMBERS_BACKUP: '/api/members/backup',
};